### ISSUE TITLE
The HTML is in a word file

### ISSUE THREAD

**Issue by Sanjit1** [angelayw17/csp2020#1]
Hello, I go to RB like you, and like helping poeple with CSP. I noticed that you wrote your HTML code in Word, so it saved a .docx file. You need to use a text edito like notepad if you are using Windows, or TextEdit if you are on a Mac. I forked your website to show you how it should look: [https://github.com/Sanjit1/csp2020](https://github.com/Sanjit1/csp2020). I hope this helps :). 

If you still need any help after that feel free to reply to this thread!

**Comment by angelayw17** [comment]
Hi Sanjit, Thanks for the help! Also I know you go to RB, we were in the same CSA class last year and you always had that minions background on zoom I think.AngelaSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Sanjit Sarda <notifications@github.com> Date: 9/6/20  12:30 PM  (GMT-08:00) To: angelayw17/csp2020 <csp2020@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [angelayw17/csp2020] The HTML is in a word file (#1) 
Hello, I go to RB like you, and like helping poeple with CSP. I noticed that you wrote your HTML code in Word, so it saved a .docx file. You need to use a text edito like notepad if you are using Windows, or TextEdit if you are on a Mac. I forked your website to show you how it should look: https://github.com/Sanjit1/csp2020. I hope this helps :).
If you still need any help after that feel free to reply to this thread!

**Comment by Sanjit1** [comment]
oop didn't realize it was you.
